name: scraper-test

on:
  workflow_dispatch:
    inputs:
      company:
        description: 'Company to scrape'
        required: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    continue-on-error: true
    services:
      # create a splash service for rendering JS pages (and disable private mode)
      splash:
        image: docker.pkg.github.com/gursahajkohli/seleniumvector/splash-disable-private:1.0
        credentials:
          username: ${{ github.repository }}
          password: ${{ github.token }}
        ports:
          - 8050:8050
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # TODO: cache virtualenv instead of pip packages?
      - name: Cache pip
        id: cache-pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: Run scraper
        run: |
          cd src/scraper
          python scraper ../../config/scraper/${SITE}.scraper.config ../../out/${SITE}.csv
        env:
          SITE: ${{ github.event.inputs.company }}
      - name: Archive CSV outputs
        uses: actions/upload-artifact@v2
        with:
          name: csv-output
          path: ./out/
          if-no-files-found: error
  filter-and-merge:
    runs-on: ubuntu-latest
    needs: scrape
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Download scraped CSV output
        uses: actions/download-artifact@v2
        with:
          name: csv-output
          path: ./out/
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # TODO: cache virtualenv instead of pip packages?
      - name: Cache pip
        id: cache-pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: Run filter
        run: |
          cd src
          python filter.py ../config/filter/ "../out/*.csv"
      - name: Archive filtered CSVs
        uses: actions/upload-artifact@v2
        with:
          name: filtered-csv-output
          path: ./out/
          if-no-files-found: error
      - name: Run merger
        run: |
          cd src/scraper/scraper
          python merger.py "../../../out/*.csv" ../../../merged.xml
      - name: Archive XMLs
        uses: actions/upload-artifact@v2
        with:
          name: xml-output
          path: ./*.xml
          if-no-files-found: error
